version: '3'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=raspi.lan,raspi.lan:443,raspi-lan:80
    env_file:
      - db.env
    depends_on:
      - db

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    volumes_from:
      - app
    depends_on:
      - app

volumes:
  db:
  nextcloud:
