version: '3.7'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
        volume:
          nocopy: true
    environment:
      - POSTGRES_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=raspi.lan,raspi.lan:443,raspi-lan:80
    env_file:
      - db.env
    depends_on:
      - db

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/certs
    volumes_from:
      - app
    depends_on:
      - app

volumes:
  db:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.7.10,nolock,soft,rw"
      device: ":/volume1/raspidata/nextcloud-db"
  nextcloud:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.7.10,nolock,soft,rw"
      device: ":/volume1/raspidata/nextcloud-data"
