version: '3'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - ./app-data/html:/var/www/html
      - ./app-data/apps:/var/www/html/custom_apps
      - ./app-data/config:/var/www/html/config
      - ./app-data/data:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=raspi.lan,raspi.lan:443,raspi-lan:80
    env_file:
      - db.env
    depends_on:
      - db

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/certs
    volumes_from:
      - app
    depends_on:
      - app

#volumes:
#  db:
#  nextcloud:
